# Generated by Django 2.2.1 on 2019-12-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_exchange', '0003_auto_20191220_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filehomework',
            old_name='file',
            new_name='file_pdf',
        ),
    ]
