# Generated by Django 2.2.1 on 2019-12-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_exchange', '0006_auto_20191223_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filehomework',
            options={'ordering': ['-nb_views']},
        ),
        migrations.AddField(
            model_name='filehomework',
            name='comment',
            field=models.TextField(default='The comment field was not existing when this file was created.', max_length=250),
            preserve_default=False,
        ),
    ]
