# Generated by Django 2.2.1 on 2019-12-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_exchange', '0007_auto_20191227_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filehomework',
            old_name='user',
            new_name='author',
        ),
    ]
