# Generated by Django 2.2.1 on 2019-12-29 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files_exchange', '0010_auto_20191228_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filehomework',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="File's author"),
        ),
        migrations.AlterField(
            model_name='filehomework',
            name='comment',
            field=models.TextField(max_length=250, verbose_name="File's description"),
        ),
        migrations.AlterField(
            model_name='filehomework',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='filehomework',
            name='promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_exchange.Promo', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='filehomework',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_exchange.School', verbose_name="School's name"),
        ),
        migrations.AlterField(
            model_name='filehomework',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_exchange.Subject', verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='filehomework',
            name='title',
            field=models.CharField(max_length=100, verbose_name="File's name"),
        ),
        migrations.AlterField(
            model_name='promo',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name="School's City"),
        ),
        migrations.AlterField(
            model_name='school',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='school',
            name='title',
            field=models.CharField(max_length=100, verbose_name="School's name"),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='typeschool',
            name='title',
            field=models.CharField(max_length=100, verbose_name="School's type"),
        ),
    ]
